### PR TITLE
Simplify face_normal code

### PR DESCRIPTION
**Pull request by raovgarimella**
Modified face_cell_ids_ to store cell ID or 1s complement of cell ID to indicate if face normal points out of or into the cell respectively. This allows the face_normal code to be much simpler.

@ecoon This required changes to MeshLogical and MeshEmbeddedLogical - please look over carefully before merging.

### CODE REVIEW

**Comment by lipnikov** [comment]
For a representative snapshot of 30000ms, in one subroutine, cost of face_normal dropped from 2690ms to 72 ms.

**Comment by raovgarimella** [comment]
Cool

**Comment by lipnikov** [comment]
I am ready to merge this PR. Any objections?

**Comment by jd-moulton** [comment]
Yes, I think it is ready.  Please go ahead and merge.

**Pull request merged**
