### PR TITLE
Upgrade BoxLib to the next version

### PR DESCRIPTION
**Pull request by lipnikov**
To keep this component alive, we need to upgrade it to the last version. It will take many baby steps. This step is from 1.3.4 to 1.3.5.

### CODE REVIEW

**Comment by jd-moulton** [comment]
Will this compile with gcc-9.x?

**Comment by lipnikov** [comment]
Do not know. Why not? I can launch  a build later. The diff between
versions was 75K lines but quite innocent. We may need to make 20+ upgrades
like that

**Comment by lipnikov** [comment]
The code has bugs for spacedim=3 and another set of bugs for spacedim=2. So
it may fail with a new compiler...

**Comment by lipnikov** [comment]
Noticed some instability with running one structured test. This PR needs more investigation.

**Comment by lipnikov** [comment]
Instability was due to the additional code added in 1.3.5 to the BoxLib initialization. It assumed silently that char** argv was not null. PR is re-opened for review.

**Pull request merged**
