### PR TITLE
Add partitioner specification to mesh factory

### PR DESCRIPTION
**Pull request by raovgarimella**
Added a method to mesh factory that allows callers to specify the partitioner to be used. Default partitioner is METIS. Changes allow us to reinstate test_deform_vols and test_columns unit tests as we can now specify that these must use ZOLTAN_RCB as the partitioner.

### CODE REVIEW

**Comment by raovgarimella** [comment]
@lipnikov suggested that the addition of partitioner to mesh_factory be propagated up to the input spec level. The latest set of commits does that.

**Comment by raovgarimella** [comment]
Updated v2.3.1-draft documentation

**Comment by raovgarimella** [comment]
BTW, @jd-moulton, the nemslice patch I sent you is supposed to be a replacement for the original patch, not an add-on

**Comment by ekikinzon** [comment]
Konstantin has already replaced the old patch by the new one (and also ran tests with it included).

**Comment by lipnikov** [comment]
Works for me.  Need on a feature branch.

**Pull request merged**
