### PR TITLE
Konstantin/hypre

### PR DESCRIPTION
**Pull request by lipnikov**
Issue #199. Added FindHypre with dependencies and replaced deprecated CMake commands. The PR  shows that CMake resolves correctly HYPRE dependencies. ATS build passed without PETSc.

### CODE REVIEW

**Comment by ecoon** [comment]
That's great, I started going down this road of imported interface properties, but not too far.  Thanks for doing this!

**Comment by ecoon** [comment]
Does this get picked up by Ifpack as well?  In the Trilinos cmake IfpackConfig.cmake it looks like the Hypre library is hard-coded -- does the Ifpack_TPL_LIST including HYPRE as a TPL mean that that dependency gets set, and therefore (since there is now a HYPRE target to resolve, and it depends upon SuperLU) this will get the full chain of dependencies?

Also, is e.g. line 163: https://github.com/amanzi/amanzi/pull/202/commits/30a51c2271647c4a5403c898fa6899107fe0fda6#diff-e6336d86377c2785203faa5cdc272e2bR163

relying on the HYPRE_DIR as the "hint" to find SuperLU correct?  I guess if you manually install HYPRE yourself, and it depends upon SuperLU, that's as good a place as any, though maybe there should be a SUPERLU_DIR hint as well in case it exists and is set by the user?

**Comment by jd-moulton** [comment]
Having trouble on Wolf, will give this a try there and let you know after lunch.

**Comment by lipnikov** [comment]
My understanding of CMake is that secondary dependencies for a target are processed correctly.

**Comment by lipnikov** [comment]
There is no global variable SUPERLU_DIR currently. We may add it to SuperBuild/templates/amanzi-tpl-config.cmake.in or we can call amanzi with -D SuperLU_LIBRARY=<name>.

**Pull request merged**
