### PR TITLE
Updates Amanzi to use a typedef'd Comm_type and encourages uniformity in use of Comms

### LINKED ISSUE #285: --enable-alquimia --disable-crunchtope
It appears that Alquimia requires building Crunchtope, but superbuild is not aware of that?  Or at least, running bootstrap with: `--enable alquimia --disable-crunchtope` happily builds Alquimia and doesn't build Crunchtope, but then inserts:

```
set(CRUNCHTOPE_DIR ${AMANZI_TPLS_INSTALL_DIR} CACHE PATH "CRUNCHTOPE installation prefix")
```

into amanzi-tpl-config.cmake anyway, and fails to configure Amanzi because it can't find the Crunchtop libraries.

### PR DESCRIPTION
**Pull request by ecoon**
This pull request references #284 and closes #285 and #286. 

All tests pass (including Simple, MSTK, and MOAB, excluding STK).

Note this touches a ton of code and slightly changes interfaces for constructing meshes.  New tests should look at how old tests now get a comm and use the mesh factory.

### CODE REVIEW

**Comment by ecoon** [comment]
1. great, I've made that the method in all cases (generation was different previously).
2. Thank you, good catch.  Put in a unique_ptr.  Really most of the mesh frameworks should move their cache into unique_ptr() to automate via RAII
3. Also good catch (debugging cruft).  Fixed.
4. comm_p is used in the line after it is grabbed.  This could be made into a one-liner, but I think it is useful to be explicit when casts are being done, it just makes it a bit clearer what the cast is coming from.
5. yep, fixed.

**Comment by ecoon** [comment]
6 is a bit trickier.  Currently those lines are set in Amanzi's TPLs config.cmake even if the TPLs were configured with ENABLE_CRUNCHTOPE=False.  

Just like every other package that we depend upon, there should be an ENABLE_* set.  I agree this needs a bit more work to make sure that SuperBuild sets those flags in the cmake. 

Yes, this will break existing TPL installations.  I'll take this out of the pull request for now, and reopen the ticket, then do a new pull request that adds this check and fixes SuperBuild to put in the required flags.

**Comment by lipnikov** [comment]
6. Probably SuperBuild/CMakeLists.txt should use the same logic in XSDK and non-XSDK branches, i.e. set *_DIR only when the package is enabled

**Comment by ecoon** [comment]
@jd-moulton  is this fixable?  Is there a way to force re-running the CI without a new commit?

**Comment by ecoon** [comment]
I've taken out the changes to ENABLE_* and moved that discussion into #285 and will do a separate pull request there.  It will make it easier to have a small, single change if/when things break TPLs

**Comment by ecoon** [comment]
Nominally the Boost stuff should have made it so that we didn't need to be as careful about the logic of what framework can construct what type of mesh from what type of file.  It should have, at compile time, detected which frameworks had which constructors.  But we don't have enough frameworks for this to really be necessary, and doing it in such a "general, compile-time traits based" way made it impossible to just read the code and understand the logic.  Oh, and it created more code than it saved.  Just a bit of over-generalization I think.

**Pull request merged**
