### PR TITLE
Update to CXX14

### PR DESCRIPTION
**Pull request by JulienLoiseau**
- Update `CMAKE_CXX_STANDARD` to 14
- Remove UniqueHelper, replaced with `#include <memory>` 
- Force Trilinos to CXX14, otherwise it defaults to 11 and errors while compiling Amanzi (cxx11::string)

### CODE REVIEW

**Review by ecoon — APPROVED** [review]
looks good to me

**Review by lipnikov — APPROVED** [review]
All tests passed.

**Comment by lipnikov** [comment]
@jd-moulton Please update TPLs in Docker and merge. Or set the version back to 0.98.2 and merge

**Comment by jd-moulton** [comment]
Update TPLs in Docker image available on dockerhub, and reran the github action.  Everything seems to be working so last call for any final checks.   As far as I'm concerned we can merge this PR.

**Pull request merged**
