### PR TITLE
Updated Amanzi to use the released version of Alquimia (v1.0.3).

### PR DESCRIPTION
**Pull request by jnjohnsonlbl**
- Updated version of Alquimia in TPLs.
- Updated source code to reflect minor changes in Alquimia's interface:
  - AlquimiaMaterialProperties -> AlquimiaProperties
  - There's a "hands-off" mode that requires an extra flag in the setup of an Alquimia interface.
  - The ReactionOperatorSplit function now takes the timestep as a double and not a double pointer.

### CODE REVIEW

**Comment by jnjohnsonlbl** [comment]
@smolins, @jd-moulton -- Here's are the changes to bring the version of Alquimia within Amanzi up to date. You probably want to assign one or two reviewers. Looks like they can be merged directly to the master branch if you see no issues.

**Comment by smolins** [comment]
I tried to build the TPLS with bootstrap and I get these errors (cannot find pflotran):

CMake Error at tools/cmake/Modules/FindPFLOTRAN.cmake:45 (message):
  Cannot locate PFLTORAN library directory
Call Stack (most recent call first):
  tools/cmake/AmanziTPL.cmake:435 (find_package)
  CMakeLists.txt:49 (include)


CMake Error at tools/cmake/Modules/FindPFLOTRAN.cmake:65 (message):
  Cannot locate PFLOTRAN library
Call Stack (most recent call first):
  tools/cmake/AmanziTPL.cmake:435 (find_package)
  CMakeLists.txt:49 (include)


-- Could NOT find PFLOTRAN (missing:  PFLOTRAN_INCLUDE_DIRS PFLOTRAN_LIBRARIES) 
CMake Warning at tools/cmake/AmanziTPL.cmake:437 (message):
  Failed to locate PFLOTRAN
Call Stack (most recent call first):
  CMakeLists.txt:49 (include)


-- Could NOT find ALQUIMIA (missing:  ALQUIMIA_LIBRARIES) 
CMake Warning at tools/cmake/AmanziTPL.cmake:448 (message):
  Failed to locate ALQUIMIA
Call Stack (most recent call first):
  CMakeLists.txt:49 (include)


==> lib=epetra
==> lib=teuchoskokkoscomm
==> lib=teuchoskokkoscompat
==> lib=teuchosremainder
==> lib=teuchosnumerics
==> lib=teuchoscomm
==> lib=teuchosparameterlist
==> lib=teuchoscore
==> lib=kokkoscore
==> lib=teuchoskokkoscomm
==> lib=teuchoskokkoscompat
==> lib=teuchosremainder
==> lib=teuchosnumerics
==> lib=teuchoscomm
==> lib=teuchosparameterlist
==> lib=teuchoscore
==> lib=kokkoscore
==> lib=hdf5
==> lib=hdf5_hl
==> lib=ascemio
-- Install Python tools and modules in: /media/data2/smolins/amanzi-new-alq/my-amanzi-build/lib/python2.7/site-packages
-- Leaving create_tpl_export_file
-- Writing target file
-- Writing evaluator registration macro file
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PFLOTRAN_LIBRARY
    linked by target "geochemistry" in directory /media/data2/smolins/amanzi-new-alq/src/common/alquimia
    linked by target "geochemistry" in directory /media/data2/smolins/amanzi-new-alq/src/common/alquimia
    linked by target "chemistry_pk" in directory /media/data2/smolins/amanzi-new-alq/src/pks/chemistry
    linked by target "chemistry_pk" in directory /media/data2/smolins/amanzi-new-alq/src/pks/chemistry
    linked by target "tRS" in directory /media/data2/smolins/amanzi-new-alq/src/structured_grid/mpc_pk/flow
    linked by target "tRS" in directory /media/data2/smolins/amanzi-new-alq/src/structured_grid/mpc_pk/flow
    linked by target "tRS_steady" in directory /media/data2/smolins/amanzi-new-alq/src/structured_grid/mpc_pk/flow
    linked by target "tRS_steady" in directory /media/data2/smolins/amanzi-new-alq/src/structured_grid/mpc_pk/flow
    linked by target "amanzi" in directory /media/data2/smolins/amanzi-new-alq/src/common/standalone_simulation_coordinator
    linked by target "amanzi" in directory /media/data2/smolins/amanzi-new-alq/src/common/standalone_simulation_coordinator
    linked by target "amanzi" in directory /media/data2/smolins/amanzi-new-alq/src/common/standalone_simulation_coordinator
    linked by target "amanzi" in directory /media/data2/smolins/amanzi-new-alq/src/common/standalone_simulation_coordinator

-- Configuring incomplete, errors occurred!

**Comment by jnjohnsonlbl** [comment]
This is unfortunate. That happened to me in the process, but I after the changes I made to AmanziTPL.cmake it built successfully for me. There is far too much entropy in this build system, and it’s still very environment-sensitive. I can attempt to shave off all the complexity, but this might take a while. Also, I’ve blown all the time I have this week to work on it, so I’ll have to take a look next week.

How are you guys going to maintain this thing?

Jeff

**Comment by jnjohnsonlbl** [comment]
By the way, Sergi--are you sure you're looking at jnjohnsonlbl:master and not amanzi:master? If you type 'git log', is the most recent commit eeca66b?

**Comment by smolins** [comment]
Yes, eeca66b. 

I think it would be most reasonable that David looks at the cmake problems, given he is already in charge of the cmake build system.

**Comment by jd-moulton** [comment]
I've reproduced Sergi's problem.  I will take a look soon and fix the CMake bits so we can test the actual Alquimia updates.

**Comment by lipnikov** [comment]
Revert tools/cmake/Modules/FindPFLOTRAN.cmake and it will work again.

**Comment by jd-moulton** [comment]
With fixes to the CMake stuff, and similar patches to the structured interface it passes all the unit/integration tests.  I will test the benchmark problems next, and then if all is well there I will make a clean version in a new pull request.  Probably not until the weekend though.

**Comment by smolins** [comment]
David

Where can I see / obtain these changes?

Thanks

Sergi

**Comment by jd-moulton** [comment]
Sergi, I've been tied up preparing for the presentation at EM tomorrow.  I could commit to my local branch and push that branch up to the public Amanzi repo for you.  I was hoping for a cleaner pull request, but probably better to just keep things moving forward.  Let me know your preference.

Thanks, David

**Comment by jd-moulton** [comment]
Sergi, I pushed this update and my fixes up as a new branch jeff/alquimia-update.  Please checkout the branch and test it.  Once we are happy with this branch we can rebase it and make a new pull request.  Should only take a day or two, just depends on time for testing.

**Comment by smolins** [comment]
Team:

I pushed some fixes to jeff/alquimia-upgrade (not related to the alquimia
upgrade but some other changes in the code like time units). Everything
seems to be working fine with alquimia itself except one thing:

At the time we upgraded alquimia we added the passing of two additional
AlquimiaProperties:

mineral_rate_cnst

and

aqueous_kinetic_rate_cnst


However, this did not exist in the input file of Amanzi. Now it does in the
2.3 spec but not in the native:

      <minerals>

        <mineral rate_constant="1.0e-9">Calcite</mineral>


      </minerals>

for mineral rate constant


and


      <dissolved_components>

        <primaries>

          <primary coefficient_of_diffusion="1.0E-9"
first_order_decay_constant="1.78577e-09">Tritium</primary>

        </primaries>

      </dissolved_components>

for aqueous rate constant


There are thus two things to do:


1. add translation of these two into native spec from 2.3

2. pass these values to the appropriate alquimia property fields


For faster turnaround, it would be great if somebody familiar with the
translator and native spec could do this. It would also help me a lot to
learn about places in the code I need to look at for future work on
heterogeneous properties.

Thanks

Sergi

On Tue, Oct 4, 2016 at 2:57 PM, David Moulton <notifications@github.com>
wrote:
>
> Sergi, I pushed this update and my fixes up as a new branch
jeff/alquimia-update. Please checkout the branch and test it. Once we are
happy with this branch we can rebase it and make a new pull request. Should
only take a day or two, just depends on time for testing.

**Comment by lipnikov** [comment]
RE: How are you guys going to maintain this thing?

Without much knowledge of OS X 10.11,  I was able to install Amanzi and run all tests. The only obstacle was the non-standard name "mpirun-openmpi-gcc6". Looks like entropy in the build system was reduced by your recent commits. Thanks.

**Pull request merged**
