### PR TITLE
Adds a new function that does bilinear interpolation in space and linear in time (lazily)

### PR DESCRIPTION
**Pull request by ecoon**
Yes, this is trilinear interpolation, but the implementation is
different than straight-up trilinear interpolation.  The matrix values
for the bilinear interpolation in space are loaded lazily, tracking
the interval in time.  This allows for long time array dimensions that would not
allow loading all data at once.

The canonical need for this is raster-based precipitation data.  We
need to interpolate from the raster in x-y, and across, e.g. daily
time slices for multiple years.

Also adds some better error handling to HDF5Reader for when reading
fails.

### CODE REVIEW

**Comment by ecoon** [comment]
@lipnikov Where does this imply more work?  In the native spec translator?  In documentation somewhere?

**Comment by ecoon** [comment]
refs #368

**Comment by lipnikov** [comment]
Q: Where does this imply more work? 
A: Are you thinking about Spec 2.x? I do not follow.

**Comment by ecoon** [comment]
I wasn't sure if you had function types in your higher level spec.  Standardized names with Dylan's Bilinear, will merge the PR when these tests pass.  Thanks!

**Comment by ecoon** [comment]
closes #368

**Pull request merged**
