### PR TITLE
Split ctest suite across multiple runners

### PR DESCRIPTION
**Pull request by rfiorella**
Splits ctest suite across three runners to reduce CI run times. Most recent CI run for this reduced time from ~2h7m to 1h7m, but compile time was unusually fast and so times closer to 1h30m should more often be expected.

Refs #773

### CODE REVIEW

**Comment by rfiorella** [comment]
Benefits from this approach will go away after updating mpich in container. Closing without merging.

**Comment by jd-moulton** [comment]
In response to @lipnikov question about adding our complete regression suite (#773).  I think it's worth considering that if we split the tests more evenly across runners, it seems like we'd gain something more in the wall clock time.   

As long as the runners are going in parallel?  ctest can split by test number, or regular expression, or labels.   Long term we should probably improve our labels.  But for this testing we could use the test numbers?

Propose we reopen this issue, and work on ctest configuration more.

**Comment by rfiorella** [comment]
@jd-moulton @lipnikov I had split by regex on this branch - happy to work on getting a split across a few runners to add more tests, but I'm not sure how to add the "missing" tests.

**Comment by rfiorella** [comment]
CI test failure here appears to be an issue with the custom-compiled MPICH in TPLs image (output from RockManager_gs2 test):

```
Unused ParmParse Variables:
[TOP]::geometry.SoilC.purpose(nvals = 1)  :: [all]
[TOP]::geometry.SoilC.type(nvals = 1)  :: [box]
[TOP]::geometry.SoilC.lo_coordinate(nvals = 2)  :: [0, 16]
[TOP]::geometry.SoilC.hi_coordinate(nvals = 2)  :: [32, 32]
[TOP]::rock.Soil1.permeability_dist(nvals = 1)  :: [uniform]
[TOP]::rock.Soil2.porosity.std(nvals = 1)  :: [0.01]
[TOP]::rock.Soil2.permeability_dist(nvals = 1)  :: [uniformAssertion failed in file src/mpid/ch3/src/ch3u_request.c at line 480: dtp_ != NULL
]
done.
/usr/lib/libmpi.so.12(+0x2ef542) [0x7fd50d098542]
/usr/lib/libmpi.so.12(+0x241fb8) [0x7fd50cfeafb8]
/usr/lib/libmpi.so.12(+0x358b5) [0x7fd50cdde8b5]
/usr/lib/libmpi.so.12(+0x2cabfe) [0x7fd50d073bfe]
/usr/lib/libmpi.so.12(+0x1f5a5c) [0x7fd50cf9ea5c]
/usr/lib/libmpi.so.12(+0x1ecfa5) [0x7fd50cf95fa5]
/usr/lib/libmpi.so.12(PMPI_Comm_free+0xed) [0x7fd50ce644ed]
/home/amanzi_user/install/tpls/lib/libcboxlib.so(_ZN18ParallelDescriptor11EndParallelEv+0xd8) [0x7fd50ef523e8]
/home/amanzi_user/install/tpls/lib/libcboxlib.so(_ZN6BoxLib8FinalizeEb+0x24a) [0x7fd50ef008ca]
/home/amanzi_user/amanzi_builddir/amanzi/src/structured_grid/materials/RockManager_gs_parallel(main+0x6a7) [0x559265d97b37]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fd50e9df083]
/home/amanzi_user/amanzi_builddir/amanzi/src/structured_grid/materials/RockManager_gs_parallel(+0x2c9e) [0x559265d97c9e]
internal ABORT - process 1
```

Running ```--enable-structured``` on local container with precompiled mpich the tests pass, but at the cost of poor run times on CI due to issues with oversubscription compiling with default mpich option ```--with-device=ch3:nemesis``` instead of ```--with-device=ch3:sock.``` Will look to see if there are other tweaks to the mpich configuration that can be made to resolve.

**Comment by rfiorella** [comment]
Downgrading custom-compiled mpich from 4.1.2 to 3.3.2 resolves the test failure, which seems to be related to changes to the ```--with-device=ch3:sock``` option. I think this PR and #781 are ready to merge - I'll remove the WIP tags.

**Review by jd-moulton — COMMENTED** [review]
Looks good, do we get -Wno-deprecated by default?   Otherwise nothing is lost for structured AMR.  Good to treat cmake version as a variable, hard coding that was weak.

**Review by jd-moulton — APPROVED** [review]
Previous commit that split tests based on serial and parallel labels is looking good now.  The two test sets are pretty well balanced and run quickly.   I think this is good to go.

**Pull request merged**
