### PR TITLE
Fix regression tests

### PR DESCRIPTION
**Pull request by quang-ha**
Key points:

* Remove test cases involved with structured meshes
* Use FIXTURES_REQUIRED and FIXTURES_SETUP to create dependent test - see [here](https://crascit.com/2016/10/18/test-fixtures-with-cmake-ctest/)
* Use new macro function in CMakeLists.txt for each test directory
* Modify observations (i.e. change observation name to lower case) to match with new output formats.

### CODE REVIEW

**Comment by lipnikov** [comment]
David, PR is not running.

**Comment by jd-moulton** [comment]
Keep in mind our docker setup doesn't test PRs yet.  The mechanism that github provides through Travis assumes a direct build on their clone in their VM.  So until I fix this, or someone makes a pull request that fixes it :-) we need to test manually. 

Konstantin, thanks for reviewing - and I assume testing given your detailed feedback.  I will try to test later tonight but if you can retest after the recent commits that would be great.

**Comment by lipnikov** [comment]
I did not test this PR. There are a few open questions.

**Comment by jd-moulton** [comment]
I understand, if you have time it would be helpful.

**Comment by quang-ha** [comment]
@lipnikov @jd-moulton 

1. and 2. I have removed those files. 

5. I have reduced tolerance in the dispersive transport down to 1e-8. These tolerance are comparing between the output from running test cases with the golden output. This also explains what 1e-4 in 4 - nothing changes in the script but only the margin difference between the golden-output and expected output.

For 3., here are all the graphs included:
[html-qth20.pdf](https://github.com/amanzi/amanzi/files/2291001/html-qth20.pdf)

And tables for others cases:

```
==> table_values_linear_flux_head_1d.txt <==
.. tabularcolumns:: |R|C|C|C|

+-------+-------+---------------+-------------+
| x [m] | z [m] | Analytic [Pa] | Amanzi [Pa] |
+-------+-------+---------------+-------------+
|  0.0  |  5.0  |  248159.9321  | 247915.2081 |
+-------+-------+---------------+-------------+
|  2.5  |  5.0  |  247915.2081  | 247915.2081 |
+-------+-------+---------------+-------------+
|  47.5 |  5.0  |  243510.1763  | 243510.1763 |
+-------+-------+---------------+-------------+
|  50.0 |  5.0  |  243265.4523  | 243265.4523 |
+-------+-------+---------------+-------------+
|  52.5 |  5.0  |  243020.7283  | 243020.7283 |
+-------+-------+---------------+-------------+
|  97.5 |  5.0  |  238615.6964  | 238615.6964 |
+-------+-------+---------------+-------------+
| 100.0 |  5.0  |  238370.9724  | 238615.6964 |
+-------+-------+---------------+-------------+

==> table_values_linear_head_head_1d.txt <==
.. tabularcolumns:: |R|C|C|C|

+---------+---------+-----------------+---------------+
|  x [m]  |  z [m]  |  Analytic [Pa]  |  Amanzi [Pa]  |
+=========+=========+=================+===============+
|   0.0   |   5.0   |   248159.9704   |  247915.2455  |
+---------+---------+-----------------+---------------+
|   2.5   |   5.0   |   247915.2455   |  247915.2455  |
+---------+---------+-----------------+---------------+
|   47.5  |   5.0   |   243510.1964   |  243510.1964  |
+---------+---------+-----------------+---------------+
|   50.0  |   5.0   |   243265.4714   |  243265.4714  |
+---------+---------+-----------------+---------------+
|   52.5  |   5.0   |   243020.7465   |  243020.7465  |
+---------+---------+-----------------+---------------+
|   97.5  |   5.0   |   238615.6974   |  238615.6974  |
+---------+---------+-----------------+---------------+
|  100.0  |   5.0   |   238370.9724   |  238615.6974  |
+---------+---------+-----------------+---------------+

==> table_values_linear_materials_parallel_1d.txt <==
+-------+-------+--------------+------------+
| x [m] | z [m] | Analytic [m] | Amanzi [m] |
+-------+-------+--------------+------------+
|  50.0 |  5.0  |   19.5000    |  19.5000   |
+-------+-------+--------------+------------+
|  0.0  |  5.0  |   20.0000    |  19.9750   |
+-------+-------+--------------+------------+
|  97.5 |  5.0  |   19.0250    |  19.0250   |
+-------+-------+--------------+------------+
| 100.0 |  5.0  |   19.0000    |  19.0250   |
+-------+-------+--------------+------------+
| 100.0 |  5.0  |   19.0000    |  19.0250   |
+-------+-------+--------------+------------+
|  2.5  |  5.0  |   19.9750    |  19.9750   |
+-------+-------+--------------+------------+
|  97.5 |  5.0  |   19.0250    |  19.0250   |
+-------+-------+--------------+------------+
|  52.5 |  5.0  |   19.4750    |  19.4750   |
+-------+-------+--------------+------------+
|  2.5  |  5.0  |   19.9750    |  19.9750   |
+-------+-------+--------------+------------+
|  50.0 |  5.0  |   19.5000    |  19.5000   |
+-------+-------+--------------+------------+
|  47.5 |  5.0  |   19.5250    |  19.5250   |
+-------+-------+--------------+------------+
|  47.5 |  5.0  |   19.5250    |  19.5250   |
+-------+-------+--------------+------------+
|  0.0  |  5.0  |   20.0000    |  19.9750   |
+-------+-------+--------------+------------+
|  52.5 |  5.0  |   19.4750    |  19.4750   |
+-------+-------+--------------+------------+
==> table_values_linear_materials_serial_1d.txt <==
+-------+-------+--------------+------------+
| x [m] | z [m] | Analytic [m] | Amanzi [m] |
+-------+-------+--------------+------------+
|  97.5 |  5.0  |   19.0045    |  19.0045   |
+-------+-------+--------------+------------+
|  0.0  |  5.0  |   20.0000    |  19.9545   |
+-------+-------+--------------+------------+
| 100.0 |  5.0  |   19.0000    |  19.0045   |
+-------+-------+--------------+------------+
|  47.5 |  5.0  |   19.1364    |  19.1364   |
+-------+-------+--------------+------------+
|  2.5  |  5.0  |   19.9545    |  19.9545   |
+-------+-------+--------------+------------+
|  50.0 |  5.0  |   19.0909    |  19.1114   |
+-------+-------+--------------+------------+
|  52.5 |  5.0  |   19.0864    |  19.0864   |
+-------+-------+--------------+------------+
```

**Comment by lipnikov** [comment]
I suggest to rename  directory “testing” to “regression” to avoid possible conflicts with OSX

**Comment by quang-ha** [comment]
What command did you use? I have tried both with bootstrap:

```
# Build Amanzi
./bootstrap.sh --prefix=/home/qth20/Documents/installed/amanzi --amanzi-build-dir=/home/qth20/Documents/amanzi/build/amanzi --tpl-config-file=/home/qth20/Documents/installed/amanzi-tpls/tpls/share/cmake/amanzi-tpl-config.cmake --parallel=4 --opt --enable-shared --enable-structured --enable-alquimia --enable-pflotran --enable-crunchtope --enable-moab_mesh --with-mpi=/home/qth20/.local/openmpi-3.1.1_gcc-7.3.0 --enable-test_suite --enable-reg_tests
```

and with cmake:

```
CMAKE=`which cmake`
CC=`which mpicc`
CXX=`which mpiCC`
F90=`which mpif90`

# Configure the Amanzi build
${CMAKE} \
  -C"/home/qth20/Documents/installed/amanzi-tpls/tpls/share/cmake/amanzi-tpl-config.cmake" \
  -DCMAKE_INSTALL_PREFIX:STRING=/home/qth20/Documents/installed/amanzi-test \
  -DCMAKE_BUILD_TYPE:STRING='Release' \
  -DCMAKE_C_COMPILER=${CC} \
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DCMAKE_Fortran_COMPILER=${F90} \
  -DENABLE_Structured:BOOL=TRUE \
  -DENABLE_Unstructured:BOOL=TRUE \
  -DENABLE_STK_Mesh:BOOL=TRUE \
  -DENABLE_MOAB_Mesh:BOOL=TRUE \
  -DENABLE_MSTK_Mesh:BOOL=TRUE \
  -DENABLE_HYPRE:BOOL=TRUE \
  -DENABLE_PETSC:BOOL=TRUE \
  -DENABLE_ALQUIMIA:BOOL=TRUE \
  -DENABLE_PFLOTRAN:BOOL=TRUE \
  -DENABLE_CRUNCHTOPE:BOOL=TRUE \
  -DENABLE_Physics:BOOL=TRUE \
  -DBUILD_SHARED_LIBS:BOOL=TRUE \
  -DCCSE_BL_SPACEDIM:INT=2 \
  -DENABLE_Regression_Tests:BOOL=TRUE \
  -DMPI_EXEC_GLOBAL_ARGS:STRING='--oversubscribe' \
  ..
```
seems to work for me. Both on Ubuntu - I haven't tested on OSX.

**Comment by lipnikov** [comment]
Did you use a clean build directory? I see no golden files in build/testing/verification/flow/richards/steady-state/unconfined_seepage_1d/

**Comment by lipnikov** [comment]
It failed on Ubuntu

**Comment by lipnikov** [comment]
Only one option triggers regression:  -DENABLE_Regression_Tests:BOOL=TRUE 
Summary:
The following tests FAILED:
	178 - compare_infiltration_clay_sand_1d_u_observation (Failed)
	180 - compare_infiltration_loam_sand_1d_u_observation (Failed)
	182 - compare_infiltration_sand_loam_1d_u_observation (Failed)
	184 - compare_unconfined_layered_2d_observation (Failed)
	186 - compare_unconfined_no_recharge_1d_observation (Failed)
	188 - compare_unconfined_recharge_1d_observation (Failed)
	190 - compare_unconfined_seepage_1d_observation (Failed)
	192 - compare_infiltration_dry_sand_1d (Failed)
	194 - compare_linear_flux_head_1d_observation (Failed)
	196 - compare_linear_head_head_1d_observation (Failed)
	198 - compare_linear_materials_parallel_1d_observation (Failed)
	200 - compare_linear_materials_serial_1d_observation (Failed)
	202 - compare_boundedDomain_2d_observation (Failed)
	204 - compare_butler_pod_2d_observation (Failed)
	206 - compare_butler_strip_2d_observation (Failed)
	208 - compare_hantush_anisotropic_2d_observation (Failed)
	210 - compare_theis_isotropic_1d_observation (Failed)
	212 - compare_dispersion_45_point_2d_observation (Failed)
	214 - compare_dispersion_aligned_point_2d_observation (Failed)

**Comment by quang-ha** [comment]
I used a clean empty `build`directory. Can I see the output of `ctest -I 178,214,2 -V` (test all case 178 to 214) from your end? It could possibly that the `golden_output` would also need to be copied over - should be a quick fix if that is the case.

**Comment by lipnikov** [comment]
Potential problem:
178:   File ".../amanzi-master/tools/testing/compare_observation_results.py", line 3, in <module>
178:     import h5py
178: ImportError: No module named h5py

But I can launch Python manually and import  h5py. I'm rebuilding user_guide to see that loaded modules work correctly,..

**Comment by quang-ha** [comment]
@lipnikov @jd-moulton 

1. Fixed naming to `test_suites`
1. Fixed `PYTHONPATH` not defined in test.

**Comment by lipnikov** [comment]
Relative tolerance is sensitive to small observation values. The robust solution is to use 2 tolerances: relative and absolute.

**Comment by lipnikov** [comment]
Relative and absolute tolerances are typically used together: | u - u_h | < rel_tol |u| + abs_tol. This way you can switch to absolute tolerance by providing "RELATIVE_TOLERANCE 0.0" or omitting this parameter. To switch to relative tolerance, we skip parameter ABSOLUTE_TOLERANCE or set it to 0.0.
When observations change from 0 to 1 and we want 5 significant digits to be correct, we set both tolerances to 1e-5.

**Comment by lipnikov** [comment]
You need relative tolerance for compare_unconfined_no_recharge_1d_observation

**Comment by quang-ha** [comment]
@lipnikov fixed for the 5 tests. @jd-moulton

**Pull request merged**
