### PR TITLE
Adds ATS as a submodule for direct compilation within Amanzi

### PR DESCRIPTION
**Pull request by ecoon**
This allows ATS to be directly downloaded from Amanzi:

```
git submodule update --init --remote
```

and then installed via bootstrap:

```
bootstrap.sh ... --disable-physics --enable-ats
```

### CODE REVIEW

**Comment by lipnikov** [comment]
I find NativePhysics and ATS not quite informative. Can we call them AmanziPhysicsModule and ATSPhysicsModule?

**Comment by ecoon** [comment]
Sure

**Comment by lipnikov** [comment]
Since your branch failed, I pushed my changes to bootstrap.sh as a part of a regulatory release code preparation. Let me know if you need help with merging your changes to bootstrap.

**Comment by ecoon** [comment]
How do you convinced Travis to rerun the test?  This is showing as failed based on an attempt 3 days ago, despite recent commits. @jd-moulton

**Comment by raovgarimella** [comment]
If you sign into the Travis CI using your github account, you will be able to see all your builds. On the top right corner, there is drop down menu which has a "Trigger Build" option


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Pull request merged**
