### PR TITLE
removes Timer, fixes compiler warnings

### PR DESCRIPTION
**Pull request by ecoon**
In doing some compiler warning cleanup (for missing return values) I noticed that we have a very-rarely-used `Timer` and `TimerManager` classes that are 10+ years old.

We also use the Teuchos::TimeMonitor functionality. 

Surely there is no need for both.

This PR removes Timer and TimerManager in favor of TimeMonitor.  Exactly what is timed has changed incrementally to use Teuchos's constructor = start, destructor=stop methodology, but only very very incrementally (a few parameter lists are pulled outside of the timed context, but all actual work is still in the timed context).

### CODE REVIEW

**Comment by ecoon** [comment]
Note I have not tested with structured, so relying on CI to do that now.

**Comment by ecoon** [comment]
@lipnikov  Can you check that this prints out something that you are happy with?  Running for instance the user guide problem, I see:

```
================================================================================

                      TimeMonitor results over 1 processor

Timer Name                  Global time (num calls)
--------------------------------------------------------------------------------
Full Simulation             6.903 (1)
Geometric Model creation    0.00032 (1)
Mesh creation               0.5806 (1)
================================================================================
Amanzi::SIMULATION_SUCCESSFUL
```

at the end of the run.

**Comment by lipnikov** [comment]
What is the output for a parallel run? We had before something line this

Full Simulation............... completed in avg=671.528, min=669.958, max=673.053 seconds.
Geometric Model creation...... completed in avg=0.000128625, min=0.000105, max=0.000169 seconds.
Mesh creation................. completed in avg=42.0982, min=41.7947, max=43.6387 seconds.

**Comment by ecoon** [comment]
```
===================================================================================================

                               TimeMonitor results over 2 processors

Timer Name                  MinOverProcs    MeanOverProcs    MaxOverProcs    MeanOverCallCounts
---------------------------------------------------------------------------------------------------
Full Simulation             5.569 (1)       5.575 (1)        5.581 (1)       5.575 (1)
Geometric Model creation    0.00029 (1)     0.000295 (1)     0.0003 (1)      0.000295 (1)
Mesh creation               1.556 (1)       1.566 (1)        1.576 (1)       1.566 (1)
===================================================================================================
Amanzi::SIMULATION_SUCCESSFUL
```

**Review by lipnikov — CHANGES_REQUESTED** [review]
Structured and unstructured tests passed on my OSX. Timings looks good for unstructured in serial and parallel. Timings were lost for Structured Amanzi.

**Review by lipnikov — APPROVED** [review]

**Pull request merged**
