### PR TITLE
Konstantin/tpls

### PR DESCRIPTION
**Pull request by lipnikov**
Support of shared libraries has been developed and tested on Ubuntu+gcc, Fedora+gcc, Fedora+clang, OSX+MacPorts+gcc, and OSX+Xcode. Although not all implemented solutions to discovered TPLs an Amanzi issues are perfect, the branch is stable with and without non-default values of LD_LIBRARY_PATH and/or DYLD_LIBRARY_PATH. Summary of implemented solutions:

1. SuperLU is a separate package now due to HYPRE and PETSc
2. Shared linking of HYPRE does not support FE interface
3. CMAKE_INSTALL_RPATH and CMAKE_INTALL_NAME_DIR are needed for all TPLs to create absolute path to shared libraries. 
4. To allow linking of shared libraries three strategies were used:  dummy files (e.g. boxlib), LINK_LIBS option of amanzi_add_library, and "-Wl, -undefiled dynamic_lookup" to allow undefined symbols. Lazy solution #3 was used for poorly designed libraries (structured Amanzi, SuperLU, etc)

### CODE REVIEW

**Comment by AlexisPerry** [comment]
I just tried building the TPL Docker image with this branch and whether I use --enable-shared or not, it dies trying to download Hypre.  Now, I've been running into and internal compiler error in the PETSc build within the Docker image build for a while now, but that is much further on in the build process.

**Comment by lipnikov** [comment]
HYPRE: probably package was rebuild  and its MD5 sum has been changed last month. We saw it before with Trilinos. Please confirm.

PETSc: Please provide OS version + compiler version + MPI version + bootstrap option for --with-mpi + PETSc build error message.

**Comment by lipnikov** [comment]
I erased Hypre and it was downloaded successfully for me. Must be something else...

**Comment by AlexisPerry** [comment]
Here is my procedure:
```
cd amanzi/Docker  

docker build --build-arg http_proxy=http://proxyout.lanl.gov:8080 --build-arg https_proxy=http://proxyout.lanl.gov:8080 -f Dockerfile-TPLs.txt -t metsi/amanzi-tpls:konstantin-tpls .
```

The OS, compiler version, etc. are all documented in the attached Dockerfile.

[Dockerfile-TPLs.txt](https://github.com/amanzi/amanzi/files/1415673/Dockerfile-TPLs.txt)

**Comment by lipnikov** [comment]
HYPRE does not configure due to cmake 3.7 features used in Build_HYPRE.cmake
PETSc fails since HYPRE died silently without installing a library. This is a very  old feature.

**Comment by jd-moulton** [comment]
Is there a way to avoid CMake 3.7 features in Build_HYPRE.cmake?

**Comment by lipnikov** [comment]
Probably by adding empty CMakeList.txt to root that calls src/CMakeList.txt

**Comment by AlexisPerry** [comment]
Have you been able to build the Docker image?  My attempts still fail to build PETSc every time.

**Comment by lipnikov** [comment]
Do you see lib/libHYPRE.so file inside your install directory? Do you see any change since yesterday after a few changes were made to the build scripts?

**Comment by AlexisPerry** [comment]
So the problem seems to be unique to building in the Docker container.  Here is the error message I get when I dump the PETSc log to the screen:
```
          CC arch-linux2-c-opt/obj/src/tao/linesearch/interface/taolinesearch.o
          FC arch-linux2-c-opt/obj/src/mat/f90-mod/petscmatmod.o
          FC arch-linux2-c-opt/obj/src/dm/f90-mod/petscdmmod.o
gfortran: internal compiler error: Killed (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
gmakefile:234: recipe for target 'arch-linux2-c-opt/obj/src/dm/f90-mod/petscdmmod.o' failed
make[5]: *** [arch-linux2-c-opt/obj/src/dm/f90-mod/petscdmmod.o] Error 4
make[5]: Leaving directory '/home/amanzi_user/amanzi_builddir/tpls/petsc/petsc-3.7.5-source'
/home/amanzi_user/amanzi_builddir/tpls/petsc/petsc-3.7.5-source/lib/petsc/conf/rules:105: recipe for target 'gnumake' failed
make[4]: *** [gnumake] Error 2
make[4]: Leaving directory '/home/amanzi_user/amanzi_builddir/tpls/petsc/petsc-3.7.5-source'
**************************ERROR*************************************
  Error during compile, check arch-linux2-c-opt/lib/petsc/conf/make.log
  Send it and arch-linux2-c-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
********************************************************************
makefile:24: recipe for target 'all' failed
make[3]: *** [all] Error 1
CMakeFiles/petsc.dir/build.make:117: recipe for target 'petsc/petsc-timestamps/petsc-build' failed
make[2]: *** [petsc/petsc-timestamps/petsc-build] Error 2
CMakeFiles/Makefile2:3144: recipe for target 'CMakeFiles/petsc.dir/all' failed
make[1]: *** [CMakeFiles/petsc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Amanzi Bootstrap ERROR: Failed to build TPLs
```
lib/libHYPRE.so exists in my install directory, and the only change is that it does indeed build HYPRE.  This PETSc error is something I've seen ever since we switched to TPL version 0.94.10.

**Comment by AlexisPerry** [comment]
Also, the TPLs build just fine on Darwin, but the Amanz build fails.

```
Scanning dependencies of target tPPH
[ 60%] Building CXX object src/structured_grid/utils/CMakeFiles/tPPH.dir/tParmParseHelpers.cpp.o
[ 60%] Building CXX object src/executables/CMakeFiles/verify_hex.dir/VerifyHex.cc.o
[ 60%] Building Fortran object src/structured_grid/utils/CMakeFiles/tPPH.dir/__/shared_dso.f90.o
[ 60%] Linking CXX executable tPPH
/usr/bin/ld: cannot find -lgeochemistry
collect2: error: ld returned 1 exit status
make[2]: *** [src/structured_grid/utils/tPPH] Error 1
make[1]: *** [src/structured_grid/utils/CMakeFiles/tPPH.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Linking CXX executable verify_hex
[ 60%] Built target verify_hex
make: *** [all] Error 2
Amanzi Bootstrap ERROR: Failed to build Amanzi
```

**Comment by lipnikov** [comment]
Build of TPLs and Amanzi on Mac OSX with LLVM worked for me using only shared boost libraries. Still these libraries are install with @rpath instead of full path.

**Comment by lipnikov** [comment]
RE: gfortran: internal compiler error: Killed (program f951)
I would compare PETSc internal logs for differences between Docker and bootstrap builds.

**Comment by lipnikov** [comment]
RE: /usr/bin/ld: cannot find -lgeochemistry
What is the dynamic section of this ELF file?

**Comment by AlexisPerry** [comment]
As of commit 98d7ef4, everything builds fine for me on Darwin.  I'll continue debugging the Docker image build, but since that was an issue before this PR I don't see any reason not to merge this request.

**Pull request merged**
