### PR TITLE
Merge alexis/docker into master

### PR DESCRIPTION
**Pull request by AlexisPerry**
This should be enough to get Travis CI up and running on master.

### CODE REVIEW

**Comment by AlexisPerry** [comment]
To test building the Docker images, here's how I do it.
```
alias lanlDockerBuild="docker build --build-arg http_proxy=http://proxyout.lanl.gov:8080 --build-arg https_proxy=http://proxyout.lanl.gov:8080"

cd amanzi/Docker
lanlDockerBuild -f Dockerfile-TPLs -t metsi/amanzi-tpls:latest .
lanlDockerBuild -f Dockerfile-Amanzi -t metsi/amanzi .
```

libssl1.0.0 was the name for the apt-get package that I found, but if we need a different one, I have no problem with changing it.  This one has worked so far.

The --parallel=8 is the result of Travis CI having a limit on how long a build can run.  If you go over that time limit, it shows your build as failing.  Basically, I needed to shorten the length of time to build Amanzi itself and this is the highest number I could get away with.

**Comment by lipnikov** [comment]
Will your instructions work for Mac?

**Comment by AlexisPerry** [comment]
Yep.  I do all my Docker build stuff on my Mac.  You have to make sure Docker is installed and running first, of course.

**Comment by lipnikov** [comment]
Loos like geochemistry is not enabled by default.

What is metsi? Do I need to use option -t ?

**Comment by AlexisPerry** [comment]
No, you don't have to use -t.  That just gives the image a name of your choosing and helps when pushing images to DockerHub repos.  metsi is the name I made up for the repo. It means "water" in Sesotho.

**Comment by lipnikov** [comment]
TPLs passed for me. I also had to changed RAM. No geochemistry packages were build.

**Comment by lipnikov** [comment]
Amanzi build failed with an internal compiler error. I increased RAM from 3G to 4G. Amanzi build was successful. But most tests failed due to missing libzoltan.so. I did not see a problem with Trilinos libraries for long time. What is CMake version for this Ubuntu container?

**Comment by raovgarimella** [comment]
I should point out that metsi (while clever) is very close to metis, the graph partitioner we include as a TPL. I first read it as metis.

**Comment by AlexisPerry** [comment]
@raovgarimella Good point.  I am not wedded to the name and it can be changed without much difficulty if someone has another idea for a name.

@lipnikov I'm fairly certain the CMake version is 3.9.1 for ubuntu:artful.  For ubuntu:latest I think it's 3.5.x.

**Comment by lipnikov** [comment]
libzoltan.so: Is there a way to run diagnostic on generated libraries? or extract them as files and study outside the container? Did you succeed to run tests?

**Comment by jd-moulton** [comment]
I wouldn't worry about the name.  It was hard to find a good URL for Docker hub.  In terms of our tags we could use something different if necessary.  If folks really do get confused then we can get creative.

**Comment by lipnikov** [comment]
Build failed due to missing Alquimia. Fixed the offending test in pks/chemistry.

**Comment by AlexisPerry** [comment]
Now that the CI build passes again, do you think it's safe to merge this PR? @lipnikov @jd-moulton

**Comment by lipnikov** [comment]
It seems that CI reports success of Amanzi build but does not report failure of tests:  36% tests passed, 93 tests failed out of 145

**Comment by AlexisPerry** [comment]
Hmm, that is definitely an issue.  I'm not familiar with how the testing is performed.  How many of those tests require that Amanzi be build with --enable-structured?

**Comment by lipnikov** [comment]
None. 
The error message is: "error while loading shared libraries: libzoltan.so.12: cannot open shared object file: No such file or directory". Zoltan should be on the list of Trilinos libraries. Strange that other tests that use Tirlinos libraries passed.

**Comment by lipnikov** [comment]
I observed exactly same error on my Mac using Docker. I mimicked your bootstrap arguments on Ubuntu 14. All tests passed.

**Comment by AlexisPerry** [comment]
So the error only occurs within the Docker container?

**Comment by lipnikov** [comment]
Yes, only within the Docker. I am running on Ubuntu 16... will update in 5 min

**Comment by lipnikov** [comment]
I looked at the executable created by Docker. I did not find obvious problems with the runtime path.

**Comment by lipnikov** [comment]
I have no objections to merge.

**Pull request merged**
