### PR TITLE
Cherry-pick doc from amanzi-0.87

### PR DESCRIPTION
**Pull request by daniellivingston**
Please review for completeness.

All commits made after 1fef1683f0fc495b425f169b9fc7395e2dd6f075 were cherry-picked into this branch, and `testing->test_suites` conflicts were resolved.

Complete list of cherry-picked hashes, in chronological order (oldest-to-newest): 

```
1fef1683f0fc495b425f169b9fc7395e2dd6f075
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

9dfb973572742e79d1abc63401915dd32677fd8b
testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d.rst

5512d71890852521ff3caab8db652035149ede44
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

3b922c374cb176ccd94a4567f4a11eb2233d0e57
testing/verification/flow/saturated/steady-state/linear_materials_serial_1d/amanzi_linear_materials_serial_1d.rst

21734d21eab5d3bc98d266764beb507d8df8f3b5
testing/verification/flow/saturated/steady-state/linear_materials_serial_1d/amanzi_linear_materials_serial_1d.py

b0558e0142b29b3356ced2b04dc4ded9b2f3a622
testing/verification/flow/saturated/steady-state/linear_materials_serial_1d/amanzi_linear_materials_serial_1d.rst

671e3a1e1627521ebd9c5c3e7b358b9b2cf2e328
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

920e4f90039eb9f03f0f5e424e4a5668287bff5b
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

75f787fb0f619c78c7fb29f7435c8aebb5c0b3b4
doc/user_guide/bib/ascem.bib

b552cb8583fb8b192551940fe74cb9d0d0b8c26b
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d-u.xml

e37380e1b25dc5b6884332e416ec046882127b0a
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

be64b73b9b58548b561a4824a0de047044fc28df
testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d.rst

6a74220b1d6b3e96e5d7109b1555b847628b9040
testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d_u.xml → testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d-u.xml

18ff2897a5dc23c7f08df978ca5e31edbc3b9aec
testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d.rst

9451812c4dfd227380fe4202d5170502539f7950
doc/user_guide/bib/ascem.bib

81470b251c2eb3095420f5f1c8324084a545bcdc
doc/user_guide/bib/ascem.bib

b2c41195831b82ede21ae3bb632bd3e6a2c09ef8
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

14c7f413307f86c3848fd6c3e455aae828163ffd
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

7a8de585014e6b59afc6c42758922d054d565550
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

0794d15f904b85a18692dad91a64d8b971d23a24
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

3440aec7c92abff73777d3ea7c0ed233521b7bd9
testing/verification/flow/richards/steady-state/unconfined_no_recharge_1d/amanzi_unconfined_no_recharge_1d.rst

003557a3f8b4945e93aa810e8876c65729db51ae
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.rst

286b1b18122c4f88baceef869dd7757911fe9f6a
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.rst

66d583036b7a3cdd06cecf087c5a116027f04eb3
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.rst

242872eb484865a7b489efd52f90b2c6c66eccff
testing/verification/flow/richards/steady-state/unconfined_seepage_1d/amanzi_unconfined_seepage_1d.rst

c73df01206c5260250c7bd4737f25113e469eef5
testing/verification/flow/richards/steady-state/unconfined_seepage_1d/amanzi_unconfined_seepage_1d.rst

3c1ffc73b64ea8c5ee3dda193244c3afcc5beac0
doc/user_guide/bib/ascem.bib

dac9ba5c620195637857a986a86a29806b919b4a
testing/verification/flow/saturated/steady-state/linear_head_head_1d/amanzi_linear_head_head_1d.rst

9a73863f48b4e2b65ab1f3ebd12ef046fed9b81a
testing/verification/flow/saturated/steady-state/linear_head_head_1d/amanzi_linear_head_head_1d.rst

015898a8820750565d1f199ebde0121268266b81
testing/verification/flow/saturated/steady-state/linear_flux_head_1d/amanzi_linear_flux_head_1d.rst

03bb6d420033f5bee69a6d530df33061068c240e
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

1fe6d130542fb740c13d316f6a682db0dc843ae4
doc/user_guide/bib/ascem.bib
testing/verification/flow/saturated/steady-state/linear_head_head_1d/amanzi_linear_head_head_1d.rst
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

e8ea3f4773fa0d1a1876e2c05aaa771433f79b87
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.py
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

ff31aa12d0ab442df06d50a7600655e67c4129c0
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.py
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.rst

d2fda89091ad9f74f181168f219a037557315ae9
testing/verification/transport/saturated/steady-state/dispersion_aligned_point_2d/amanzi_dispersion_aligned_point_2d.rst

0f8cec274579364766da4fda3d97ba707de4a834
testing/verification/flow/richards/steady-state/unconfined_no_recharge_1d/amanzi_unconfined_no_recharge_1d.rst
testing/verification/flow/richards/steady-state/unconfined_seepage_1d/amanzi_unconfined_seepage_1d.rst

816642e3bc8d87624b545769665cf88583ecde7a
testing/verification/transport/saturated/steady-state/dispersion_45_point_2d/amanzi_dispersion_45_point_2d.rst

25a2d59815647cc00b6d317657ad703dd7a0010e
testing/verification/transport/saturated/steady-state/dispersion_45_point_2d/amanzi_dispersion_45_point_2d.rst

----- Skipping "Minor cleanup of regression tests." (ed45151ce30fd8b0ecf4b1f4996ffb3a0d857840) to "Updates flow verification tests to adhere to xml schema " (a9e70b22ad8b4f55c36c5008e54c235619331d29)


82223a92e7abe1b577c9273a6bad693d598c6467
testing/verification/flow/saturated/steady-state/linear_flux_head_1d/amanzi_linear_flux_head_1d.rst

ba5efd57e7f27c81e36343e85ac049f0d47fda83
testing/verification/flow/saturated/steady-state/linear_flux_head_1d/amanzi_linear_flux_head_1d.rst

761675ce395c77ee3442a79110e30ede211364fd
testing/verification/flow/saturated/steady-state/linear_flux_head_1d/amanzi_linear_flux_head_1d.rst

27294fb34311b75ca81a6779906da738dfe05e32
testing/verification/transport/saturated/steady-state/dispersion_aligned_point_2d/amanzi_dispersion_aligned_point_2d.rst

b40a57fcdde7a3ce0e3d4cb10fe4e18fec3202e6
testing/verification/transport/saturated/steady-state/dispersion_aligned_point_2d/amanzi_dispersion_aligned_point_2d.rst

de82e52f814b098db9f574ecd95fc50d8291f89a
testing/verification/transport/saturated/steady-state/dispersion_aligned_point_2d/amanzi_dispersion_aligned_point_2d.rst

b404a3388e4280c99176793796556b09c48d3bfb
testing/verification/transport/saturated/steady-state/dispersion_aligned_point_2d/amanzi_dispersion_aligned_point_2d.rst

a6d4764baf301c9bc9dee7a382c56d95b87b0c3a
testing/verification/transport/saturated/steady-state/dispersion_45_point_2d/amanzi_dispersion_45_point_2d.rst

92312f3de5704dd290fe9f3d6ecfbbad84a29d66
testing/verification/flow/richards/steady-state/unconfined_seepage_1d/amanzi_unconfined_seepage_1d.rst

492b3e6196bc48d5788f7350b16487f2bbe925bc
testing/verification/flow/richards/steady-state/unconfined_no_recharge_1d/amanzi_unconfined_no_recharge_1d.rst

de031715210dcbd0feeb7697d830af5148aeb660
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

fbab2875a45d2e15135c8f835249363dd528fa3e
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

f798dc7cfe9f662c073e34e216c6ec361fab7031
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

049b30d5ff4f0fd6009db87f89717fb04d1387ce
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

7f1e193b0e3f64cbf09bcf74f0636f50e3ebe435
doc/user_guide/bib/ascem.bib
testing/verification/flow/richards/steady-state/infiltration_clay_sand_1d/amanzi_infiltration_clay_sand_1d.rst

5150e76e747b683de8cdac69f8431c321ceeb9ad
doc/user_guide/bib/ascem.bib
testing/verification/flow/richards/steady-state/infiltration_clay_sand_1d/amanzi_infiltration_clay_sand_1d.rst

f421f8c5ad93635ae5d81a1d81434870ef86337d
testing/verification/flow/richards/steady-state/unconfined_seepage_1d/amanzi_unconfined_seepage_1d.rst

0430256bc1d5d9be4be1c7cfad846070951defc0
testing/verification/flow/saturated/transient/boundedDomain_2d/amanzi_boundedDomain_2d.rst

3e797e538a7ab1e4b8a23c2cf1ee35bf0c884c0d
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst
testing/verification/flow/saturated/transient/theis_isotropic_1d/amanzi_theis_isotropic_1d.rst

fbde7859c5ff2cd1d4628afbd8c2bc492549e725
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

52df836799a37d74505394737799eacec9eeb741
testing/verification/flow/saturated/transient/hantush_anisotropic_2d/amanzi_hantush_anisotropic_2d.rst

e68dbcaf028b85f6b4f98726ead00e3ed9633bac
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

a4cb366cc94058539caf5ab29399ecb6aeae2b1c
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

1d8f4f8a0e63e505595fe5f8cbf8da637a51fbc2
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

d7f6099e4302624ab6107519ae7d5f474b0c0a3e
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

1e0f7de965208d2050dec1db2cd782ee7558562c
testing/verification/flow/saturated/transient/butler_strip_2d/amanzi_butler_strip_2d.rst

a424f942129239f5781af610066a41897d86786d
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

cf3b75e12efe483cdcd9ad84d87432702b045660
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

48db350fefec6efef3166253f6a4bc5dbd08ad84
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

f5df77b32cde34700be6c91f39bdff9b07b73fca
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

e15337f8a824bfd47e5fd9a554bf37e01884b8d4
testing/verification/flow/saturated/transient/butler_pod_2d/amanzi_butler_pod_2d.rst

5ea74bc0612fb9728865436136e5198c1c761348
testing/verification/flow/saturated/steady-state/linear_materials_parallel_1d/amanzi_linear_materials_parallel_1d.rst

----- Skipping "Minor updates to the schema, mostly addressing missing elements" (de956e0da9450610ee6a46d321d181d5847a2f38) to "minor fix to python script for tracer test" (1a56a5c029839902c9025791839d84d319a1b8a9)
```

### CODE REVIEW

**Comment by daniellivingston** [comment]
@johnportiz14 , you may want to look at this as well. We are merging your documentation changes from branch `amanzi-0.87` into master.

**Comment by johnportiz14** [comment]
Looks good to me, Daniel!

John P. Ortiz

**Comment by lipnikov** [comment]
Daniel, did you build the user guide?

**Comment by daniellivingston** [comment]
Hi @lipnikov , I did. Have you noticed something weird?

The user guide build seems fine, sans warnings that were there before John's changes were added:

```
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/background/getting_started.rst:22: WARNING: undefined label: bootstrap (if the link has no caption the label must precede a section header)
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/capabilities/chemistry.rst:98: WARNING: undefined label: sec-benchmarks-chemistry (if the link has no caption the label must precede a section header)
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/capabilities/chemistry.rst:106: WARNING: undefined label: sec-benchmarks-chemistry (if the link has no caption the label must precede a section header)
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/input/chemistry.rst:18: WARNING: unknown document: ../benchmarking/chemistry/index
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/input/index.rst:6: WARNING: undefined label: color function region (if the link has no caption the label must precede a section header)
/Users/livingston/playground/amanzi-no-compile/doc/user_guide/input/input_schema.rst:953: WARNING: Could not lex literal_block as "xml". Highlighting skipped.
```

**Pull request merged**
