### PR TITLE
Fix/tpetra/csr densevector

### PR DESCRIPTION
**Pull request by JulienLoiseau**
- Adding type depending on Kokkos CUDA in AmanziType: AmanziDeviceSpace, AmanziShareSpace, AmanziHostSpace
- CSR and DenseVector memory space
- Parallel scan in CSR 
- DenseVector added in Op.hh to avoid allocation at every iterations

### CODE REVIEW

**Comment by JulienLoiseau** [comment]
Will we use UVM for long or will we start to go to separated memory space for performances? Once the features like Assemble or Pre conditioner. 
If HIP and ROCm backend does not provides anything like UVM we will have to do the work of separating them anyways.

**Comment by ecoon** [comment]
I have to admit I thought that most of what we had didn't assume UVM.  The only real difference would be if we had not called deep_copy() when moving things from CPU to GPU (which is a no-op in Kokkos::Serial/OpenMP/CudaUVM, but does the copy in Kokkos::Cuda).

**Comment by ecoon** [comment]
I guess this can be checked easily enough, by turning off UVM in the Kokkos build and seeing if things compile and tests pass.

**Comment by JulienLoiseau** [comment]
To remove uvm we would use dual view in the cache for things that are used by both Host/Device. 
If nothing is used on Host, yes just have them on the device space as a simple view (or the CSR). 

Should I work on removing UVM while you work on having a base for assemble? I am sure we would have a great benefit especially in the use of the mesh cache. 

For the deep_copy between two memory space we just need to use mirrors: https://github.com/kokkos/kokkos/wiki/View#643-deep-copy-and-hostmirror

Did you tried to compile this merge without UVM? Serial or OpenMP?

**Comment by JulienLoiseau** [comment]
Oh note that I had to comment in CMakeLists because it complains that there was no CMakeLists in Physics directory

**Comment by ecoon** [comment]
Sorry, this ended up taking longer than I expected to get ironed out.  The key was realizing that a UVM host mirror view is not on Kokkos::Serial::memory_space, but instead that Kokkos::Serial can access Kokkos::CudaUVMSpace natively.  So for instance, you can't get a UVM "dual view" on Kokkos::DefaultHostMemorySpace.  So we really need each of the following spaces:

* DefaultDeviceMemorySpace (Kokkos::DefaultExecutionSpace::memory_space, e.g. Kokkos::CudaUVMSpace if we're enabling UVM)
* DefaultHostMemorySpace ( Kokkos::DefaultHostExecutionSpace::memory_space, e.g. Kokkos::HostSpace)
* MirrorHost::memory_space (Not sure how to get this generically, but it is the host_mirror_space of the DualView, which in the case of UVM, is Kokkos::CudaUVMSpace, but in the case of not-UVM-Cuda, would be Kokkos::HostSpace.).
* DeviceOnlyMemorySpace (Kokkos::CudaSpace when there is UVM enabled -- for optimization purposes).

I also then typedef 3 devices:

* Amanzi::DefaultDevice, the device, used for executing device code.
* Amanzi::DefaultHost, the host, used for executing host-only code
* Amanzi::MirrorHost, the host execution space with CudaUVMSpace as the memory space -- this is needed for CompositeVector::ViewComponent<MirrorHost>() to get the view on the CPU -- ViewComponent<DefaultHost>() does not work!

And we may eventually need 
* Amanzi::DeviceOnly, a device with no UVM?  Or maybe this is never used, as our templating so far is simply on the memory space.  But if we start templating kernels too, we may need the execution space as well, at which point we would need that device.


If this all makes sense to you Julien, I think we're good to merge this.  Tests pass on both Summit and my mac.

**Comment by ecoon** [comment]
Some odd warnings.  These look like maybe the nonmember functions need to be templated with the memory space to match the template parameter on the class?  But everything still works...

```
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:380:61: warning: friend declaration 'Amanzi::WhetStone::Tensor<MEMSPACE> Amanzi::WhetStone::operator*(const Amanzi::WhetStone::Tensor<MEMSPACE>&, const Amanzi::WhetStone::Tensor<MEMSPACE>&)' declares a non-template function [-Wnon-template-friend]
   friend Tensor operator*(const Tensor& T1, const Tensor& T2);
                                                             ^
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:380:61: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here)
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:448:68: warning: friend declaration 'std::ostream& Amanzi::WhetStone::operator<<(std::ostream&, const Amanzi::WhetStone::Tensor<MEMSPACE>&)' declares a non-template function [-Wnon-template-friend]
   friend std::ostream& operator<<(std::ostream& os, const Tensor& T);
                                                                    ^
[ 47%] Linking CXX shared library libwhetstone.so
[ 47%] Built target whetstone
[ 47%] Building CXX object src/whetstone/CMakeFiles/whetstone_misc.dir/test/Main.cc.o
[ 47%] Building CXX object src/whetstone/CMakeFiles/whetstone_misc.dir/test/whetstone_tensors.cc.o
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:380:61: warning: friend declaration 'Amanzi::WhetStone::Tensor<MEMSPACE> Amanzi::WhetStone::operator*(const Amanzi::WhetStone::Tensor<MEMSPACE>&, const Amanzi::WhetStone::Tensor<MEMSPACE>&)' declares a non-template function [-Wnon-template-friend]
   friend Tensor operator*(const Tensor& T1, const Tensor& T2);
                                                             ^
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:380:61: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here)
/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi/repos/dev-tpetra/src/whetstone/Tensor.hh:448:68: warning: friend declaration 'std::ostream& Amanzi::WhetStone::operator<<(std::ostream&, const Amanzi::WhetStone::Tensor<MEMSPACE>&)' declares a non-template function [-Wnon-template-friend]
   friend std::ostream& operator<<(std::ostream& os, const Tensor& T);

```

**Comment by ecoon** [comment]
I also get some strange warnings about destructors not being __host__ __device__, also doesn't seem to matter.  Do we care?


```
[ 56%] Building CXX object src/mesh_functions/CMakeFiles/mesh_functions.dir/MeshFunction.cc.o
/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::RCP") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::basic_string") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::~RCP") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::RCP") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::basic_string") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("") is not allowed

/sw/summit/cuda/10.1.243/include/vector_types.h(421): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::~RCP") from a __host__ __device__ function("") is not allowed

/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi-tpls/install-dev-tpetra/trilinos-12-14-1_master/lib/cmake/Teuchos/../../../include/Cuda/KokkosExp_Cuda_IterateTile_Refactor.hpp(131): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("Amanzi::Patch::~Patch") is not allowed

/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi-tpls/install-dev-tpetra/trilinos-12-14-1_master/lib/cmake/Teuchos/../../../include/Cuda/KokkosExp_Cuda_IterateTile_Refactor.hpp(131): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::~RCP") from a __host__ __device__ function("Amanzi::Patch::~Patch") is not allowed

/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi-tpls/install-dev-tpetra/trilinos-12-14-1_master/lib/cmake/Teuchos/../../../include/Cuda/KokkosExp_Cuda_IterateTile_Refactor.hpp(131): warning #2928-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("Amanzi::Patch::~Patch [subobject]") is not allowed

/ccs/home/ecoon/geo132/proj-work/amanzi_ats/amanzi-tpls/install-dev-tpetra/trilinos-12-14-1_master/lib/cmake/Teuchos/../../../include/Cuda/KokkosExp_Cuda_IterateTile_Refactor.hpp(131): warning #2928-D: calling a __host__ function("Teuchos::RCP<const  ::Amanzi::AmanziMesh::Mesh> ::~RCP") from a __host__ __device__ function("Amanzi::Patch::~Patch [subobject]") is not allowed
```

**Pull request merged**
