### PR TITLE
Lifting facesets onto surface mesh

### PR DESCRIPTION
**Pull request by daniellivingston**
Addresses #48. Moves critical code into `build_set` from `get_set_entities_and_vofs`.

### CODE REVIEW

**Comment by ecoon** [comment]
Based on these tests, it looks like your changes fix set_get_entities() (yay!) but not valid_set_name().  You have some false negatives -- some of the things you say are not valid are valid.  Should be a quick fix -- I can push an updated one if you want, but you might as well finish the job since it is 90% there!

**Comment by jd-moulton** [comment]
We hadn't been looking closely at valid_set_name(), we at least I haven't been.  I would say push your update to this code so we don't get bogged down here.  We have @daniellivingston starting on another case that I think is very helpful for boundary conditions on the surface mesh.  Specifically, we want a face set on the side of a 3D mesh to be lifted to an edge set on the 2D surface mesh (e.g., for outlets or non-headwater boundaries).  

Related question is if you are counting on this branch to be merged soon to master so you can use these features/fixes there.  Once you update valid_set_name(), it sounds like we could merge and pick up the other changes later.

**Comment by ecoon** [comment]
@jd-moulton  and @daniellivingston , that case, i.e. a FACE of the 3D volumetric mesh going to a FACE of the 2D surface mesh is tested in my unit test and already works.

**Comment by jd-moulton** [comment]
Modulo @lipnikov comment, which we can resolve in next iteration, I think this part is ready and I should accept it.  Then I think @daniellivingston can start a new branch from current master for the next phase of this work.  Let me know if you agree by updating your review status.

**Comment by ecoon** [comment]
@lipnikov I'm not sure if I'd call that a false positive or not.  It returns valid_set_name() == true, but then set_get_entities() does not throw and returns an empty set.  Similarly if you ask for CELLs of a subsurface FACE set that do not coincide with the surface.  

I don't have a huge problem with returning valid_set_name() == true for these cases (since set_get_entities() doesn't error and, at least conceptually, they are valid sets), but if you think that valid_set_name() == true should instead imply a NONEMPTY set is returned from set_get_entities(), we could easily add a call to get_set_entities() in valid_set_name() and check the length.

To me the most important contract is that valid_set_name() implies that get_set_entities() won't throw.

**Comment by ecoon** [comment]
@jd-moulton what is the next phase of this work?  Did you see my above comment?  I think your example already works.

**Comment by jd-moulton** [comment]
We couldn't see any code that would generate an appropriate edge set in the 3D mesh and then elevate that to the derived surface mesh as a face set.  We are also pretty sure that our current ability to read labeled sets does not include edge sets.  But if some or all of these capabilities are  there that would be great.

**Comment by lipnikov** [comment]
@jd-moulton  I think this code is inside inherit_labeled_set() function. It lifts edges of side sets to faces of top surface. The name implies that it will not work for other regions.

**Comment by lipnikov** [comment]
@ecoon I am fine with the current behavior of valid_set_name. Regarding derived meshes, we need MeshExtractedManifold class for meshing fracture networks, due to MSTK unstable algorithms for intersecting fractures.

**Pull request merged**
